### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-semantic-html#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://ravedave.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/semantic-html/1) criteria:
- [x] include a [`header`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) element with the name of your blog and a tagline
- [x] include a [`footer`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer) element with copyright information and a design credit
- [x] include either a working [`video`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) or [`audio`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) element (you can use other sources, but `http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4` is a good video source and `http://www.w3schools.com/tags/horse.mp3` is a good audio source)
- [x] include at least 2 blog posts (of at least one sentence each)
- [x] include the [`main`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main), [`article`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article), [`section`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section), [`blockquote`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote), [`figure`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure), and [`figcaption`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) elements, in contexts where they make semantic sense
- [x] return no errors (warnings are OK) when uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)

**Comment by chrisvfritz** [comment]
The music is... maddening, but the code looks good! :+1: :shipit:
